import Foundation
import Testing

@testable import Tamga

/// One entry from `Fixtures/MachineFiles/manifest.json`, describing a real
/// `.machine` file produced by the tamga-api server's own
/// `encode_machine_file`.
///
/// These fixtures are NOT generated by this repo, and tests must not generate
/// their own to stand in for them. Every SDK in this fleet previously verified
/// its machine-file reader against a file it had encoded itself, so both sides
/// shared one misreading of the wire format and CI stayed green for two years
/// while no SDK could open anything the server actually emitted. See
/// `Fixtures/MachineFiles/PROVENANCE.md`.
///
/// The suite iterates `MachineFileFixture.all` rather than naming files, so
/// fixtures added to the manifest are picked up with no edit here.
struct MachineFileFixture: Sendable, CustomStringConvertible {
    /// The manifest key, e.g. `rsa_pss_encrypted_valid`.
    let name: String
    /// The file name inside the fixture directory.
    let file: String
    /// The exact `alg` string the server wrote into the certificate.
    let alg: String
    /// Whether `enc` is AES-256-GCM ciphertext rather than plain base64.
    let encrypted: Bool
    /// Whether `enc` is the `"<nonce_b64>.<cipher_b64>"` pair. Stated by the
    /// manifest so a test can assert the SDK's reading of the format against
    /// the generator's, instead of against its own assumption.
    let encIsDotSeparated: Bool
    /// The account public key, base64, exactly as the server's API publishes
    /// it: 32 raw bytes for Ed25519, a 65-byte uncompressed X9.63 point for
    /// ECDSA P-256, and PKCS#1 `RSAPublicKey` DER for RSA.
    let publicKeyB64: String
    /// The `kid` claim the signed payload carries.
    let kid: String
    /// The license key an encrypted fixture's HKDF needs. `nil` for plain ones.
    let licenseKey: String?
    /// The machine fingerprint: HKDF `info`, and the value inside the payload.
    let fingerprint: String
    /// Whether the signed `exp` claim is already in the past relative to `iat`.
    let expired: Bool
    /// The signing scheme, as the server's `LicenseScheme` variant name.
    let scheme: String

    var description: String { name }

    /// The caller-supplied scheme this fixture must be verified under.
    ///
    /// `nil` for a scheme this SDK does not model, which a test should surface
    /// as a failure rather than skip. Both the Rust variant spelling and the
    /// API wire value are accepted: the manifest generator has used each at
    /// different times, and a fixture set that silently stops matching is
    /// worse than one that fails loudly.
    var licenseScheme: LicenseScheme? {
        switch scheme {
        case "Ed25519Sign", "ED25519_SIGN": return .ed25519Sign
        case "EcdsaP256Sign", "ECDSA_P256_SIGN": return .ecdsaP256Sign
        case "Rsa2048Pkcs1Sign", "RSA_2048_PKCS1_SIGN": return .rsa2048Pkcs1Sign
        case "Rsa2048Pkcs1PssSign", "RSA_2048_PKCS1_PSS_SIGN": return .rsa2048Pkcs1PssSign
        case "Rsa2048JwtRs256", "RSA_2048_JWT_RS256": return .rsa2048JwtRs256
        default: return nil
        }
    }

    var publicKey: Data? { Data(base64Encoded: publicKeyB64) }

    /// The raw PEM text of the fixture file.
    func pem() throws -> String {
        try String(contentsOf: Self.directory.appendingPathComponent(file), encoding: .utf8)
    }

    /// The fixture's `{enc, sig, alg}` certificate, read WITHOUT going through
    /// `MachineFile` -- so a test can rebuild a deliberately-tampered variant
    /// without depending on the type under test to take it apart.
    func certificate() throws -> Certificate {
        let body = try pem()
            .split(separator: "\n")
            .dropFirst()
            .dropLast()
            .joined()
        guard let json = Data(base64Encoded: body),
              let object = try JSONSerialization.jsonObject(with: json) as? [String: String],
              let enc = object["enc"], let sig = object["sig"], let alg = object["alg"]
        else {
            throw FixtureError.malformed("fixture \(name) is not a {enc, sig, alg} PEM certificate")
        }
        return Certificate(enc: enc, sig: sig, alg: alg)
    }

    /// The raw `{enc, sig, alg}` triple, as read straight out of the PEM.
    struct Certificate {
        let enc: String
        let sig: String
        let alg: String
    }

    /// Re-wraps this fixture's certificate with one field replaced, keeping the
    /// original signature. Used to build the downgrade and tamper cases.
    ///
    /// `alg` is outside the signature -- the server signs `enc`'s bytes and
    /// nothing else -- so an `alg` rewritten this way still carries a
    /// cryptographically valid signature. That is not a flaw in the fixture;
    /// it is the exact reason `alg` has to be parsed strictly rather than
    /// trusted.
    func rewrapped(enc: String? = nil, alg: String? = nil) throws -> String {
        let certificate = try certificate()
        return CheckoutFixture.wrapMachinePEM(
            enc: enc ?? certificate.enc,
            sig: certificate.sig,
            alg: alg ?? certificate.alg
        )
    }

    enum FixtureError: Error, CustomStringConvertible {
        case malformed(String)

        var description: String {
            switch self {
            case .malformed(let message): return message
            }
        }
    }

    // MARK: - Loading

    static let directory: URL = {
        guard let url = Bundle.module.url(forResource: "MachineFiles", withExtension: nil) else {
            fatalError(
                "MachineFileFixture: the MachineFiles resource directory is missing from the test bundle. " +
                "Check Package.swift's testTarget `resources:` entry."
            )
        }
        return url
    }()

    /// Every fixture the manifest lists, in a stable order.
    static let all: [MachineFileFixture] = {
        let manifestURL = directory.appendingPathComponent("manifest.json")
        guard let data = try? Data(contentsOf: manifestURL) else {
            fatalError("MachineFileFixture: could not read \(manifestURL.path)")
        }
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        guard let entries = try? decoder.decode([String: Entry].self, from: data) else {
            fatalError("MachineFileFixture: manifest.json did not decode as [String: Entry]")
        }
        return entries
            .sorted { $0.key < $1.key }
            .map { name, entry in
                MachineFileFixture(
                    name: name,
                    file: entry.file,
                    alg: entry.alg,
                    encrypted: entry.encrypted,
                    encIsDotSeparated: entry.encIsDotSeparated,
                    publicKeyB64: entry.publicKeyB64,
                    kid: entry.kid,
                    licenseKey: entry.licenseKey,
                    fingerprint: entry.fingerprint,
                    expired: entry.expired,
                    scheme: entry.scheme
                )
            }
    }()

    /// Fixtures whose `alg` declares `suffix` as its signing algorithm.
    ///
    /// Selecting by declared suffix rather than by file name keeps the suite
    /// manifest-driven: a renamed or added fixture is still found.
    static func declaring(signingSuffix suffix: String) -> [MachineFileFixture] {
        all.filter { $0.alg.contains("+\(suffix)+") }
    }

    private struct Entry: Decodable {
        let file: String
        let alg: String
        let encrypted: Bool
        let encIsDotSeparated: Bool
        let publicKeyB64: String
        let kid: String
        let licenseKey: String?
        let fingerprint: String
        let expired: Bool
        let scheme: String
    }
}

extension TamgaCheckoutError {
    /// The case name alone, so a test can assert WHICH failure happened
    /// without pinning the human-readable message text.
    ///
    /// Telling the cases apart is the point of several of these tests: an
    /// expired file and a forged one must not arrive as the same outcome, and
    /// neither must a downgraded `alg` and a failed decrypt.
    var caseName: String {
        switch self {
        case .offlineFileFormat: return "offlineFileFormat"
        case .signatureVerificationFailed: return "signatureVerificationFailed"
        case .decryptionFailed: return "decryptionFailed"
        case .unsupportedAlgorithm: return "unsupportedAlgorithm"
        case .expired: return "expired"
        case .schemeNotSupported: return "schemeNotSupported"
        case .ttlInvalid: return "ttlInvalid"
        }
    }
}

extension MachineFileFixture {
    /// This fixture's signed claims, read without the expiry gate firing.
    ///
    /// `now: 0` is before every fixture's `exp`, so `now - tolerance > exp` is
    /// false for all of them and the claims come back even for the ones the
    /// manifest marks expired. Callers then re-verify at a meaningful clock.
    func claims() throws -> LicenseFileClaims {
        guard let scheme = licenseScheme, let publicKey else {
            throw FixtureError.malformed("fixture \(name) has no usable scheme or public key")
        }
        return try MachineFile.parse(pem()).verifyWithClaims(
            scheme: scheme, publicKey: publicKey,
            licenseKey: licenseKey ?? "", fingerprint: fingerprint,
            now: 0
        ).claims
    }

    /// Bumps exactly one base64 character, leaving the string valid base64 and
    /// leaving any `.` framing in place -- so the tampered payload still
    /// decodes, and a verifier that ran the decode before the signature check
    /// would get further than it should.
    static func tampering(_ enc: String) -> String {
        let substitutions: [Character: Character] = ["A": "B", "B": "C", "C": "D", "a": "b", "b": "c"]
        var result = ""
        var replaced = false
        for character in enc {
            if !replaced, let replacement = substitutions[character] {
                result.append(replacement)
                replaced = true
            } else {
                result.append(character)
            }
        }
        return result
    }
}

/// Runs `body`, expecting it to throw a `TamgaCheckoutError`, and hands the
/// error back so a caller can assert WHICH one it was.
func checkoutError(
    _ body: () throws -> Void,
    sourceLocation: SourceLocation = #_sourceLocation
) -> TamgaCheckoutError? {
    do {
        try body()
        Issue.record("expected a TamgaCheckoutError, but the call succeeded", sourceLocation: sourceLocation)
        return nil
    } catch let error as TamgaCheckoutError {
        return error
    } catch {
        Issue.record("expected a TamgaCheckoutError, got \(error)", sourceLocation: sourceLocation)
        return nil
    }
}
