import Foundation
import Testing

@testable import Tamga

/// One entry from `Fixtures/Fingerprint/fingerprint.json`.
///
/// The fixture is NOT generated by this SDK. Its hashes come from an
/// independent SHA-256 implementation, because a vector an SDK produced can
/// only prove that SDK agrees with itself -- the same trap the machine-file
/// fixtures exist to avoid (`Fixtures/MachineFiles/PROVENANCE.md`). It is
/// copied into the test bundle so this suite needs no network and no sibling
/// checkout.
struct FingerprintVector: Decodable, Sendable, CustomStringConvertible {
    let name: String
    let components: [[String]]
    let canonical: String
    let fingerprint: String

    var description: String { name }

    /// The fixture writes the separator as the display placeholder `<US>`
    /// because a raw `0x1f` in a JSON file is unreadable in a diff. The byte
    /// that gets hashed is the real U+001F.
    var expectedCanonical: String { canonical.replacingOccurrences(of: "<US>", with: "\u{1F}") }

    var parsed: [TamgaFingerprint.Component] {
        components.map { .init(label: $0[0], value: $0[1]) }
    }
}

/// One entry from the fixture's `rejected` list.
struct RejectedFingerprintVector: Decodable, Sendable, CustomStringConvertible {
    let name: String
    let components: [[String]]
    let reason: String

    var description: String { "\(name) (\(reason))" }

    var parsed: [TamgaFingerprint.Component] {
        components.map { .init(label: $0[0], value: $0[1]) }
    }
}

struct FingerprintFixture: Decodable {
    let vectors: [FingerprintVector]
    let rejected: [RejectedFingerprintVector]

    static let loaded: FingerprintFixture = {
        guard let url = Bundle.module.url(forResource: "Fingerprint", withExtension: nil)?
            .appendingPathComponent("fingerprint.json"),
            let data = try? Data(contentsOf: url),
            let fixture = try? JSONDecoder().decode(FingerprintFixture.self, from: data)
        else {
            fatalError("Fixtures/Fingerprint/fingerprint.json is missing from the test bundle.")
        }
        return fixture
    }()
}

@Suite("Fingerprint canonicalisation")
struct FingerprintTests {
    // MARK: - The shared vectors

    @Test("every shared vector's canonical string reproduces",
          arguments: FingerprintFixture.loaded.vectors)
    func canonicalMatchesVector(_ vector: FingerprintVector) throws {
        #expect(try TamgaFingerprint.canonical(vector.parsed) == vector.expectedCanonical)
    }

    @Test("every shared vector's fingerprint reproduces",
          arguments: FingerprintFixture.loaded.vectors)
    func fingerprintMatchesVector(_ vector: FingerprintVector) throws {
        #expect(try TamgaFingerprint.compute(vector.parsed) == vector.fingerprint)
    }

    @Test("every rejection in the shared vectors throws rather than repairing",
          arguments: FingerprintFixture.loaded.rejected)
    func rejectedVectorThrows(_ vector: RejectedFingerprintVector) {
        #expect(throws: TamgaFingerprintError.self) {
            _ = try TamgaFingerprint.compute(vector.parsed)
        }
    }

    /// The fixture is loaded, not inlined, so a shrunk or renamed file would
    /// otherwise silently reduce this suite to nothing.
    @Test("the fixture actually carries the full vector set")
    func fixtureIsComplete() {
        #expect(FingerprintFixture.loaded.vectors.count == 9)
        #expect(FingerprintFixture.loaded.rejected.count == 8)
    }

    /// The fixture is read as `Data` and handed to `JSONDecoder`, which is
    /// byte-oriented and reads the encoding from the JSON itself. That is
    /// deliberate: `String(contentsOf:)` **without an explicit encoding
    /// guesses**, and swift-corelibs-foundation does not have to guess the same
    /// way Darwin does -- which would make this SDK disagree with *itself*
    /// across two operating systems, the one failure the shared vectors cannot
    /// catch because CI would be green on both legs separately.
    ///
    /// tamga-python hit exactly this: `Path.read_text()` picked up cp1252 on
    /// `windows-latest` and the `é` hashed as mojibake. Only the non-ASCII
    /// vector can detect it -- the other eight are pure ASCII and survive a
    /// mis-decoding reader unchanged -- so this asserts the bytes directly
    /// rather than trusting that the vector merely loaded.
    @Test("the non-ASCII vector survives the file read as UTF-8, not as locale bytes")
    func fixtureIsReadAsUTF8() throws {
        let cafe = try #require(vector("non_ascii_value"))
        let value = try #require(cafe.components.first?.last)
        // "café" NFC: 63 61 66 C3 A9. Under cp1252 the same file's bytes would
        // arrive as "cafÃ©" (five scalars) and hash differently.
        #expect(Array(value.utf8) == [0x63, 0x61, 0x66, 0xC3, 0xA9])
        #expect(value.unicodeScalars.count == 4)
        #expect(value == "caf\u{00E9}")

        // And the end-to-end consequence, which is what actually breaks.
        #expect(try TamgaFingerprint.compute(cafe.parsed) == cafe.fingerprint)
    }

    // MARK: - The three invariants that matter most

    /// Ordering is the caller's convenience, not part of the identity. A port
    /// that forgets to sort passes `single` and fails only here.
    @Test("component order does not change the fingerprint")
    func orderIndependence() throws {
        let sorted = try #require(vector("two_sorted"))
        let unsorted = try #require(vector("two_unsorted"))
        #expect(sorted.components != unsorted.components)
        #expect(try TamgaFingerprint.compute(sorted.parsed)
            == TamgaFingerprint.compute(unsorted.parsed))
    }

    /// The footgun this helper exists to absorb: the same machine typed with a
    /// stray space must not take a second seat.
    @Test("surrounding whitespace does not change the fingerprint")
    func whitespaceEquivalence() throws {
        let plain = try #require(vector("single"))
        let padded = try #require(vector("whitespace_trimmed"))
        #expect(plain.components != padded.components)
        #expect(try TamgaFingerprint.compute(plain.parsed)
            == TamgaFingerprint.compute(padded.parsed))
    }

    /// Case folding is deliberately absent: lowercasing a base64 or hex
    /// identifier corrupts it, so these must stay two machines.
    @Test("case is preserved, so a different case is a different machine")
    func casePreserved() throws {
        let lower = try #require(vector("single"))
        let upper = try #require(vector("case_preserved"))
        #expect(try TamgaFingerprint.compute(lower.parsed)
            != TamgaFingerprint.compute(upper.parsed))
    }

    // MARK: - The Swift-specific traps

    /// The sort key is the **whole `label=value` component**, not the label
    /// alone. The two orderings diverge exactly when one label is a prefix of
    /// another and the next label byte is below `=` (`0x3d`) -- `"a!"` and
    /// `"a"` here, where byte order puts `a!=z` first because `!` (`0x21`)
    /// precedes `=`, while sorting by label alone puts `a` first.
    ///
    /// Canonical string and hash both computed independently (Python
    /// `hashlib`), not by this SDK.
    @Test("the sort key is the whole component, not just the label")
    func sortKeyIsTheWholeComponent() throws {
        let components: [TamgaFingerprint.Component] = [
            .init(label: "a!", value: "z"),
            .init(label: "a", value: "y")
        ]
        #expect(try TamgaFingerprint.canonical(components)
            == "tamga-fingerprint-v1\u{1F}a!=z\u{1F}a=y")
        #expect(try TamgaFingerprint.compute(components)
            == "b7b61ad8287a9c802d74af7a6ee2b589ea714b1d8ce1a6ae33bba83c3c4815a5")

        // What a label-only sort would have produced, so the failure message
        // names the mistake rather than just showing two hashes.
        #expect(try TamgaFingerprint.compute(components)
            != "349601954aaa08ad88140d69726ec6e8fc717d853c371e6b633156d56d0b4352")
    }

    /// The sort is case-**sensitive**, because it is on bytes and uppercase
    /// ASCII (`0x41`-`0x5A`) precedes lowercase (`0x61`-`0x7A`). A
    /// case-insensitive sort reverses this pair, which is the second mutation
    /// that bites in every port. No shared vector reaches it -- every label in
    /// the fixture is lowercase -- so canonical string and hash here were
    /// computed independently (Python `hashlib`).
    @Test("the sort is case-sensitive, so an uppercase label sorts first")
    func sortIsCaseSensitive() throws {
        let components: [TamgaFingerprint.Component] = [
            .init(label: "Z", value: "1"),
            .init(label: "a", value: "2")
        ]
        #expect(try TamgaFingerprint.canonical(components)
            == "tamga-fingerprint-v1\u{1F}Z=1\u{1F}a=2")
        #expect(try TamgaFingerprint.compute(components)
            == "d8385e4f48e7396bfaafab43461e389a6575c06115531596b619fe10d916ec2a")

        // What a case-insensitive sort would have produced.
        #expect(try TamgaFingerprint.compute(components)
            != "6d5076ca37f7ceb15cad0d373c5ea48b2b70db24bf146bbfb5e62a30cad07c78")
    }

    /// The sort is bytewise on UTF-8, which is the rule as written. Under
    /// *this* rule's own label constraint it is not distinguishable from
    /// sorting the components as `String`s, and that is worth recording rather
    /// than pretending otherwise: labels are ASCII printable `0x21`-`0x7E`
    /// without `=` and are unique, so the first differing byte of two
    /// components always falls inside the ASCII label region or on the `=`
    /// that terminates it -- and the `=` sits between label and value, so a
    /// combining mark opening a value can never compose backwards into the
    /// label. Measured exhaustively over single-character and prefix-shaped
    /// labels crossed with hostile values: 7,587,405 pairs, zero divergences.
    ///
    /// Note which axis this is on. Bytewise UTF-8 order and code-point order
    /// are the *same* ordering -- UTF-8 is designed so that byte comparison
    /// reproduces code-point comparison -- so there is nothing to distinguish
    /// there and no test should pretend otherwise. Swift's `String` diverges on
    /// a third axis entirely: canonical equivalence, which can call two
    /// strings *equal* where their bytes differ.
    ///
    /// Remove the label constraint and that divergence is immediate, which is
    /// what this pins. Sorting `[UInt8]` is therefore the spelling that stays
    /// correct if a future rule ever loosens the label alphabet.
    @Test("String collation and byte order part company once labels are out of the way")
    func stringCollationDivergesOnRawValues() {
        let decomposed = "cafe\u{0301}"
        let composed = "caf\u{00E9}"
        #expect(decomposed == composed)
        #expect((decomposed < composed) == false)
        #expect((composed < decomposed) == false)
        #expect(Array(decomposed.utf8).lexicographicallyPrecedes(Array(composed.utf8)))
    }

    /// A non-ASCII label is rejected outright, so the vector above is the only
    /// way non-ASCII reaches the sort -- through a value.
    @Test("the non_ascii_value vector pins byte order through a value too")
    func nonASCIIValueSortsBytewise() throws {
        let cafe = try #require(vector("non_ascii_value"))
        #expect(try TamgaFingerprint.compute(cafe.parsed) == cafe.fingerprint)
    }

    /// The whitespace set is ASCII only. `CharacterSet.whitespacesAndNewlines`
    /// -- the obvious Foundation reach -- also covers U+00A0 and U+2028, and
    /// trimming those would make this port disagree with the seven that have no
    /// Unicode tables.
    @Test("non-ASCII whitespace is hashed, not trimmed")
    func unicodeWhitespaceIsNotTrimmed() throws {
        let plain = try TamgaFingerprint.compute([.init(label: "id", value: "a")])
        let nbsp = try TamgaFingerprint.compute([.init(label: "id", value: "\u{00A0}a")])
        let lineSeparator = try TamgaFingerprint.compute([.init(label: "id", value: "a\u{2028}")])
        #expect(plain != nbsp)
        #expect(plain != lineSeparator)

        // Confirms the Foundation call this deliberately avoids would have
        // folded both onto `plain`.
        #expect("\u{00A0}a".trimmingCharacters(in: .whitespacesAndNewlines) == "a")
        #expect("a\u{2028}".trimmingCharacters(in: .whitespacesAndNewlines) == "a")
    }

    /// NFC is deliberately absent. `"café"` composed and decomposed are one
    /// machine to a human and two to this rule, which is the documented cost of
    /// a rule eight ports can implement identically.
    @Test("Unicode normalisation is absent, and that is the documented contract")
    func unicodeIsNotNormalised() throws {
        let composed = "caf\u{00E9}"
        let decomposed = "cafe\u{0301}"
        #expect(composed == decomposed)  // Swift's own `==` folds them.
        #expect(Array(composed.utf8) != Array(decomposed.utf8))

        let first = try TamgaFingerprint.compute([.init(label: "owner", value: composed)])
        let second = try TamgaFingerprint.compute([.init(label: "owner", value: decomposed)])
        #expect(first != second)

        // And the composed form is the one the shared vector pins.
        #expect(first == (try #require(vector("non_ascii_value"))).fingerprint)
    }

    // MARK: - Rejections, named

    @Test("each rejection reports its own cause")
    func rejectionsAreDistinguished() {
        expectError(.noComponents) { try TamgaFingerprint.compute([]) }
        expectError(.emptyLabel) {
            try TamgaFingerprint.compute([.init(label: "", value: "x")])
        }
        expectError(.invalidLabel("a=b")) {
            try TamgaFingerprint.compute([.init(label: "a=b", value: "x")])
        }
        expectError(.invalidLabel("a\u{1F}b")) {
            try TamgaFingerprint.compute([.init(label: "a\u{1F}b", value: "x")])
        }
        expectError(.invalidLabel("café")) {
            try TamgaFingerprint.compute([.init(label: "café", value: "x")])
        }
        expectError(.invalidLabel("a b")) {
            try TamgaFingerprint.compute([.init(label: "a b", value: "x")])
        }
        expectError(.duplicateLabel("id")) {
            try TamgaFingerprint.compute([
                .init(label: "id", value: "a"), .init(label: "id", value: "b")
            ])
        }
        expectError(.controlCharacterInValue(label: "id")) {
            try TamgaFingerprint.compute([.init(label: "id", value: "a\u{1F}b")])
        }
        expectError(.controlCharacterInValue(label: "id")) {
            try TamgaFingerprint.compute([.init(label: "id", value: "a\u{07}b")])
        }
    }

    /// Trimming runs before validation, so whitespace-only is a legal empty
    /// value while an inner control character is still a rejection. Getting
    /// that order backwards would reject the first and accept the second.
    @Test("trim happens before validation, not after")
    func trimPrecedesValidation() throws {
        let whitespaceOnly = try TamgaFingerprint.compute([.init(label: "id", value: " \t\n")])
        let empty = try TamgaFingerprint.compute([.init(label: "id", value: "")])
        #expect(whitespaceOnly == empty)

        // A trailing control character that is NOT whitespace is not trimmed
        // away by the same pass, so it still has to throw.
        expectError(.controlCharacterInValue(label: "id")) {
            try TamgaFingerprint.compute([.init(label: "id", value: "a\u{07}")])
        }
    }

    /// The domain prefix is what stops a future v2 rule colliding with v1, so
    /// it has to actually be in the hashed input.
    @Test("the domain prefix is part of the hashed input")
    func domainPrefixIsHashed() throws {
        let canonical = try TamgaFingerprint.canonical([.init(label: "id", value: "a")])
        #expect(canonical.hasPrefix(TamgaFingerprint.version + "\u{1F}"))
        #expect(TamgaFingerprint.version == "tamga-fingerprint-v1")
    }

    /// 64 lowercase hex characters, because the server column takes anything
    /// and would happily store a 200-character accident.
    @Test("the fingerprint is 64 lowercase hex characters")
    func fingerprintShape() throws {
        let fingerprint = try TamgaFingerprint.compute([.init(label: "id", value: "a")])
        #expect(fingerprint.count == 64)
        #expect(fingerprint.allSatisfy { $0.isHexDigit && !$0.isUppercase })
    }

    // MARK: - Helpers

    private func vector(_ name: String) -> FingerprintVector? {
        FingerprintFixture.loaded.vectors.first { $0.name == name }
    }

    private func expectError(
        _ expected: TamgaFingerprintError,
        sourceLocation: SourceLocation = #_sourceLocation,
        _ body: () throws -> String
    ) {
        do {
            let value = try body()
            Issue.record("expected \(expected) but got '\(value)'", sourceLocation: sourceLocation)
        } catch let error as TamgaFingerprintError {
            #expect(error == expected, sourceLocation: sourceLocation)
        } catch {
            Issue.record("expected \(expected) but got \(error)", sourceLocation: sourceLocation)
        }
    }
}
